services:
  - type: web
    name: cinematrix-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USERNAME
        sync: false
      - key: REDDIT_PASSWORD
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: IMDB_API_KEY
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_ACCESS_TOKEN
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
